### ISSUE TITLE
POIで例外を吐く

### ISSUE THREAD

**Issue by T45K** [T45K/CRIONE#38]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 78
	at java.lang.String.substring(String.java:1963) ~[na:1.8.0_181]
	at gr.uom.java.xmi.diff.MovedClassToAnotherSourceFolder.getRenamePattern(MovedClassToAnotherSourceFolder.java:16) ~[CRIONE.jar:na]
	at gr.uom.java.xmi.diff.UMLModelDiff.getMoveClassRefactorings(UMLModelDiff.java:669) ~[CRIONE.jar:na]
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:720) ~[CRIONE.jar:na]
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:138) [CRIONE.jar:na]
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97) [CRIONE.jar:na]
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:245) [CRIONE.jar:na]
	at jp.ac.osaka_u.ist.sdl.crione.repositoryMining.RefactoringMinerKt.mining(RefactoringMiner.kt:13) [CRIONE.jar:na]
	at jp.ac.osaka_u.ist.sdl.crione.MainKt.main(Main.kt:21) [CRIONE.jar:na]
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 78
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:102)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:245)
	at jp.ac.osaka_u.ist.sdl.crione.repositoryMining.RefactoringMinerKt.mining(RefactoringMiner.kt:13)
	at jp.ac.osaka_u.ist.sdl.crione.MainKt.main(Main.kt:21)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 78
	at java.lang.String.substring(String.java:1963)
	at gr.uom.java.xmi.diff.MovedClassToAnotherSourceFolder.getRenamePattern(MovedClassToAnotherSourceFolder.java:16)
	at gr.uom.java.xmi.diff.UMLModelDiff.getMoveClassRefactorings(UMLModelDiff.java:669)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:720)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97)
	... 3 more
```

**Comment by T45K** [comment]
最新版では修正済み?

**Comment by T45K** [comment]
最新版はNPEで落ちる模様

**Comment by T45K** [comment]
最新コミット版ではNPEを吐く

**Comment by T45K** [comment]
NPEというよりかはKotlilnでの例外の扱いが悪いっぽい
Javaで確認してみる

**Comment by T45K** [comment]
修正されたのでバージョンを上げる
