### ISSUE TITLE
Tokenizerでエラー

### ISSUE THREAD

**Issue by T45K** [T45K/CRIONE#54]
```
Exception in thread "main" org.eclipse.jdt.core.compiler.InvalidInputException: Underscores_In_Literals_Not_Below_17
	at org.eclipse.jdt.internal.core.util.PublicScanner.consumeDigits(PublicScanner.java:766)
	at org.eclipse.jdt.internal.core.util.PublicScanner.consumeDigits(PublicScanner.java:754)
	at org.eclipse.jdt.internal.core.util.PublicScanner.scanNumber(PublicScanner.java:3702)
	at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:1763)
	at jp.ac.osaka_u.ist.sdl.crione.cloneSearch.LexerKt.getTokenList(Lexer.kt:17)
	at jp.ac.osaka_u.ist.sdl.crione.cloneSearch.CloneSearcherKt.searchFromSingleSourceCode(CloneSearcher.kt:9)
	at jp.ac.osaka_u.ist.sdl.crione.cloneSearch.CloneSearcherKt.searchFromSingleSourceCode$default(CloneSearcher.kt:8)
	at jp.ac.osaka_u.ist.sdl.crione.cloneSearch.CloneSearcherKt.search(CloneSearcher.kt:6)
	at jp.ac.osaka_u.ist.sdl.crione.MainKt.main(Main.kt:31)
```

**Comment by T45K** [comment]
CRIONEの問題じゃない
