### ISSUE TITLE
checkoutでconflictが起きる

### ISSUE THREAD

**Issue by T45K** [T45K/CRIONE#56]
```
Exception in thread "main" org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files:
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:285)
	at jp.ac.osaka_u.ist.sdl.crione.repositoryMining.MyRepository.checkout(MyRepository.kt:13)
	at jp.ac.osaka_u.ist.sdl.crione.MainKt.main(Main.kt:25)
```

**Comment by T45K** [comment]
とりあえず一旦`git checkout .`を叩いてからやる

**Comment by T45K** [comment]
`checkout .` はInvalidRefNameExceptioになる
stashかなぁ...

**Comment by T45K** [comment]
`git.reset().setMode(ResetCommand.ResetType.HARD).setRef("HEAD").call()`
ええかんじ

**Comment by T45K** [comment]
でもなさそう

**Comment by T45K** [comment]
一旦close
